### ISSUE TITLE
Custom control for Properties manipulation Tasks

### ISSUE THREAD

**Issue by farfilli** [rmcanany/SolidEdgeHousekeeper#106]
Replace the gazillion controls in the Properties Input Editor with a custom control for each row. The control will return the data for the task to be executed.

@rmcanany you can assign this issue to me

**Comment by rmcanany** [comment]
Sounds good.

**Comment by rmcanany** [comment]
In playing with this just now, I had an idea to house the Find/Replace types in a ComboBox, rather than separate checkboxes.  It would consume less real estate.  It might also make it more logical to enable a TabStop, which could make interacting with the form more fluid.  

Another thing -- the selection column is way too wide.  It's like that because I placed the row manipulation buttons in the same column.  There must be a better way.

Anyway, this is not pressing at all.  Just wanted to make note of it in case either of us gets to it.

**Comment by rmcanany** [comment]
Superseded with https://github.com/rmcanany/SolidEdgeHousekeeper/issues/123.  Closing.

**Comment by farfilli** [comment]
@rmcanany I don't see any custom control that replaces all the individual combos and dictionaries and all the code written to handle them. Perhaps we can postpone this for the next release?
