### ISSUE TITLE
Usage of the current Solid Edge session

### ISSUE THREAD

**Issue by farfilli** [rmcanany/SolidEdgeHousekeeper#73]
What about an option to be able to use the current Solid Edge session?
It would be great to not interrupt the current works, it happens that I need to update only a few files and the need to close everything and reopen at the end is very annoying.

Perhaps you can add a control to use this new option only if the number of files to process is less than 50?

What do you think?

**Comment by rmcanany** [comment]
I like it!  

The only reason I did that in the first place was to eliminate the possibility of messing up a user's work in case SE crashed.  Before I implemented Jason's IsolatedTaskProxy, that was a regular occurrence.  Now about the only time I ever see it is with corrupted files.  Come to think of it, that happens with SEApp.Open().  I bet I could simply enclose that in a Try/Catch block.  I'll take a look at that.

I need to think through how to handle files that are already open.  Right now I automatically close any file that gets processed, but that would not be hard to change.  I would also need to disable the automatic periodic closing and reopening of SE.  That feature, again because of IsolatedTaskProxy, probably isn't needed any more anyway.

Thank you for the idea!
